// Code generated by gotdgen, DO NOT EDIT.

package tg

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"go.uber.org/multierr"

	"github.com/gotd/td/bin"
	"github.com/gotd/td/tdjson"
	"github.com/gotd/td/tdp"
	"github.com/gotd/td/tgerr"
)

// No-op definition for keeping imports.
var (
	_ = bin.Buffer{}
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = multierr.AppendInto
	_ = sort.Ints
	_ = tdp.Format
	_ = tgerr.Error{}
	_ = tdjson.Encoder{}
)

// BotBusinessConnection represents TL type `botBusinessConnection#8f34b2f5`.
type BotBusinessConnection struct {
	// Flags field of BotBusinessConnection.
	Flags bin.Fields
	// Disabled field of BotBusinessConnection.
	Disabled bool
	// ConnectionID field of BotBusinessConnection.
	ConnectionID string
	// UserID field of BotBusinessConnection.
	UserID int64
	// DCID field of BotBusinessConnection.
	DCID int
	// Date field of BotBusinessConnection.
	Date int
	// Rights field of BotBusinessConnection.
	//
	// Use SetRights and GetRights helpers.
	Rights BusinessBotRights
}

// BotBusinessConnectionTypeID is TL type id of BotBusinessConnection.
const BotBusinessConnectionTypeID = 0x8f34b2f5

// Ensuring interfaces in compile-time for BotBusinessConnection.
var (
	_ bin.Encoder     = &BotBusinessConnection{}
	_ bin.Decoder     = &BotBusinessConnection{}
	_ bin.BareEncoder = &BotBusinessConnection{}
	_ bin.BareDecoder = &BotBusinessConnection{}
)

func (b *BotBusinessConnection) Zero() bool {
	if b == nil {
		return true
	}
	if !(b.Flags.Zero()) {
		return false
	}
	if !(b.Disabled == false) {
		return false
	}
	if !(b.ConnectionID == "") {
		return false
	}
	if !(b.UserID == 0) {
		return false
	}
	if !(b.DCID == 0) {
		return false
	}
	if !(b.Date == 0) {
		return false
	}
	if !(b.Rights.Zero()) {
		return false
	}

	return true
}

// String implements fmt.Stringer.
func (b *BotBusinessConnection) String() string {
	if b == nil {
		return "BotBusinessConnection(nil)"
	}
	type Alias BotBusinessConnection
	return fmt.Sprintf("BotBusinessConnection%+v", Alias(*b))
}

// TypeID returns type id in TL schema.
//
// See https://core.telegram.org/mtproto/TL-tl#remarks.
func (*BotBusinessConnection) TypeID() uint32 {
	return BotBusinessConnectionTypeID
}

// TypeName returns name of type in TL schema.
func (*BotBusinessConnection) TypeName() string {
	return "botBusinessConnection"
}

// TypeInfo returns info about TL type.
func (b *BotBusinessConnection) TypeInfo() tdp.Type {
	typ := tdp.Type{
		Name: "botBusinessConnection",
		ID:   BotBusinessConnectionTypeID,
	}
	if b == nil {
		typ.Null = true
		return typ
	}
	typ.Fields = []tdp.Field{
		{
			Name:       "Disabled",
			SchemaName: "disabled",
			Null:       !b.Flags.Has(1),
		},
		{
			Name:       "ConnectionID",
			SchemaName: "connection_id",
		},
		{
			Name:       "UserID",
			SchemaName: "user_id",
		},
		{
			Name:       "DCID",
			SchemaName: "dc_id",
		},
		{
			Name:       "Date",
			SchemaName: "date",
		},
		{
			Name:       "Rights",
			SchemaName: "rights",
			Null:       !b.Flags.Has(2),
		},
	}
	return typ
}

// SetFlags sets flags for non-zero fields.
func (b *BotBusinessConnection) SetFlags() {
	if !(b.Disabled == false) {
		b.Flags.Set(1)
	}
	if !(b.Rights.Zero()) {
		b.Flags.Set(2)
	}
}

// Encode implements bin.Encoder.
func (b *BotBusinessConnection) Encode(buf *bin.Buffer) error {
	if b == nil {
		return fmt.Errorf("can't encode botBusinessConnection#8f34b2f5 as nil")
	}
	buf.PutID(BotBusinessConnectionTypeID)
	return b.EncodeBare(buf)
}

// EncodeBare implements bin.BareEncoder.
func (b *BotBusinessConnection) EncodeBare(buf *bin.Buffer) error {
	if b == nil {
		return fmt.Errorf("can't encode botBusinessConnection#8f34b2f5 as nil")
	}
	b.SetFlags()
	if err := b.Flags.Encode(buf); err != nil {
		return fmt.Errorf("unable to encode botBusinessConnection#8f34b2f5: field flags: %w", err)
	}
	buf.PutString(b.ConnectionID)
	buf.PutLong(b.UserID)
	buf.PutInt(b.DCID)
	buf.PutInt(b.Date)
	if b.Flags.Has(2) {
		if err := b.Rights.Encode(buf); err != nil {
			return fmt.Errorf("unable to encode botBusinessConnection#8f34b2f5: field rights: %w", err)
		}
	}
	return nil
}

// Decode implements bin.Decoder.
func (b *BotBusinessConnection) Decode(buf *bin.Buffer) error {
	if b == nil {
		return fmt.Errorf("can't decode botBusinessConnection#8f34b2f5 to nil")
	}
	if err := buf.ConsumeID(BotBusinessConnectionTypeID); err != nil {
		return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: %w", err)
	}
	return b.DecodeBare(buf)
}

// DecodeBare implements bin.BareDecoder.
func (b *BotBusinessConnection) DecodeBare(buf *bin.Buffer) error {
	if b == nil {
		return fmt.Errorf("can't decode botBusinessConnection#8f34b2f5 to nil")
	}
	{
		if err := b.Flags.Decode(buf); err != nil {
			return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: field flags: %w", err)
		}
	}
	b.Disabled = b.Flags.Has(1)
	{
		value, err := buf.String()
		if err != nil {
			return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: field connection_id: %w", err)
		}
		b.ConnectionID = value
	}
	{
		value, err := buf.Long()
		if err != nil {
			return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: field user_id: %w", err)
		}
		b.UserID = value
	}
	{
		value, err := buf.Int()
		if err != nil {
			return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: field dc_id: %w", err)
		}
		b.DCID = value
	}
	{
		value, err := buf.Int()
		if err != nil {
			return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: field date: %w", err)
		}
		b.Date = value
	}
	if b.Flags.Has(2) {
		if err := b.Rights.Decode(buf); err != nil {
			return fmt.Errorf("unable to decode botBusinessConnection#8f34b2f5: field rights: %w", err)
		}
	}
	return nil
}

// SetDisabled sets value of Disabled conditional field.
func (b *BotBusinessConnection) SetDisabled(value bool) {
	if value {
		b.Flags.Set(1)
		b.Disabled = true
	} else {
		b.Flags.Unset(1)
		b.Disabled = false
	}
}

// GetDisabled returns value of Disabled conditional field.
func (b *BotBusinessConnection) GetDisabled() (value bool) {
	if b == nil {
		return
	}
	return b.Flags.Has(1)
}

// GetConnectionID returns value of ConnectionID field.
func (b *BotBusinessConnection) GetConnectionID() (value string) {
	if b == nil {
		return
	}
	return b.ConnectionID
}

// GetUserID returns value of UserID field.
func (b *BotBusinessConnection) GetUserID() (value int64) {
	if b == nil {
		return
	}
	return b.UserID
}

// GetDCID returns value of DCID field.
func (b *BotBusinessConnection) GetDCID() (value int) {
	if b == nil {
		return
	}
	return b.DCID
}

// GetDate returns value of Date field.
func (b *BotBusinessConnection) GetDate() (value int) {
	if b == nil {
		return
	}
	return b.Date
}

// SetRights sets value of Rights conditional field.
func (b *BotBusinessConnection) SetRights(value BusinessBotRights) {
	b.Flags.Set(2)
	b.Rights = value
}

// GetRights returns value of Rights conditional field and
// boolean which is true if field was set.
func (b *BotBusinessConnection) GetRights() (value BusinessBotRights, ok bool) {
	if b == nil {
		return
	}
	if !b.Flags.Has(2) {
		return value, false
	}
	return b.Rights, true
}
